# Generated by Django 4.1.2 on 2022-10-10 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contatti', '0003_contatto_ruolo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contatto',
            name='nominativo',
        ),
        migrations.AddField(
            model_name='contatto',
            name='cognome',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contatto',
            name='nome',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
