# Generated by Django 4.1.2 on 2022-10-19 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contatti', '0005_interview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='interview',
            field=models.CharField(max_length=1000),
        ),
    ]
