# Generated by Django 4.1.2 on 2022-10-10 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denominazione', models.CharField(max_length=100)),
                ('indirizzo', models.CharField(max_length=100)),
                ('cap', models.CharField(max_length=5)),
                ('città', models.CharField(max_length=100)),
                ('provincia', models.CharField(max_length=4)),
                ('telefono', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=50)),
                ('partita_iva', models.CharField(max_length=11)),
            ],
        ),
    ]
